CD-4137
codescan-io/sonarqube pull request #341
Opened 2023-09-04 22:00 UTC by arunsimha-cs

Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our roadmap and expectations. Therefore, we typically only accept minor cosmetic changes and typo fixes. If you would like to see a new feature, please create a new thread in the forum ["Suggest new features"](https://community.sonarsource.com/c/suggestions/features).

With that in mind, if you would like to submit a code contribution, make sure that you adhere to the following guidelines and all tests are passing (Travis build is executed for each pull request):

- [ ] Please explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [ ] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
- [ ] Provide a unit test for any code you changed
- [ ] If there is a [JIRA](http://jira.sonarsource.com/browse/SONAR) ticket available, please make your commits and pull request start with the ticket ID (SONAR-XXXX)

We will try to give you feedback on your contribution as quickly as possible.

Thank You!
The SonarSource Team

2023-09-07 08:30 UTC, anurag-ar requested changes

2023-09-07 08:30 UTC, anurag-ar commented on server/sonar-webserver-webapi/src/main/java/org/sonar/server/usertoken/ws/RevokeAction.java
> +      logger.info("Revoke token request by user: {} and token name: {}", user.getLogin(), name);
@arunsimha-cs System Administrators can revoke any user's token.
Log message is incorrect. What we are displaying is the **user whose token is being revoked** and not the user who placed the revoke request.

<img width="1331" alt="Screenshot 2023-09-07 at 1 54 45 PM" src="https://github.com/codescan-io/sonarqube/assets/74111708/b84cf036-5822-470a-944e-03d84124807d">

2023-09-07 08:33 UTC, lokeswarayadav-ar approved these changes

2023-09-08 07:39 UTC, anurag-ar approved these changes

2023-09-08 08:58 UTC, merged